name: RNN-ML-env

channels:
  - conda-forge
  - defaults

dependencies:
  - python = 3.9.13
  - numpy = 1.23.3
  - matplotlib = 3.5.3
  - pytorch = 1.12.1
  - seaborn = 0.11.2
  - pip
  - jupyter
  - tqdm
